<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use Illuminate\Support\Carbon; // Tambahkan ini di bagian atas

class LowonganSeeder extends Seeder
{
    public function run(): void
    {
        // Hapus data lama
        DB::table('lowongan')->truncate();
        $now = Carbon::now();

        $dummyJobs = [
            [
                'job_name' => 'Admin Assistant',
                'category_job' => 'Admin & Operations',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Any',
                'education_minimal' => 'High School',
                'experience_minimal' => '1 year',
                'age' => '22-30',
                'job_description' => 'Manage office administration and daily operations.',
                'job_requirements' => 'Good communication and organizational skills',
                'salary_minimal_range' => 3000000,
                'maximum_salary_range' => 4500000,
                'location' => 'Pungging',
                'image_banner' => null,
                'company_name' => 'Mitra Admin',
                'company_description' => 'Company specializing in office management services.',
                'company_address' => 'Jl. Raya Mojokerto No. 5',
                'social_media_company' => '@mitraadmin',
                'company_industry' => 'Administration',
                'company_logo_image' => null,
                'email_company' => 'hr@mitraadmin.com',
                'no_wa_company' => '081298765432',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Sales Executive',
                'category_job' => 'Business Dev & Sales',
                'job_type' => 'Part-Time',
                'place_work' => 'Remote',
                'type_gender' => 'Any',
                'education_minimal' => 'Diploma',
                'experience_minimal' => '3 years',
                'age' => '25-40',
                'job_description' => 'Drive sales and expand customer base.',
                'job_requirements' => 'Negotiation skills, CRM experience',
                'salary_minimal_range' => 4000000,
                'maximum_salary_range' => 7000000,
                'location' => 'Prajurit Kulon',
                'image_banner' => null,
                'company_name' => 'SalesPro',
                'company_description' => 'Sales consultancy firm.',
                'company_address' => 'Jl. Kebon Jeruk No. 22',
                'social_media_company' => '@salespro',
                'company_industry' => 'Sales & Marketing',
                'company_logo_image' => null,
                'email_company' => 'contact@salespro.com',
                'no_wa_company' => '081233344455',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Customer Service Officer',
                'category_job' => 'CS & Hospitality',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Female',
                'education_minimal' => 'Bachelor Degree',
                'experience_minimal' => '2 years',
                'age' => '23-33',
                'job_description' => 'Handle customer inquiries and complaints.',
                'job_requirements' => 'Friendly attitude, communication skills',
                'salary_minimal_range' => 3500000,
                'maximum_salary_range' => 5000000,
                'location' => 'Gedeg',
                'image_banner' => null,
                'company_name' => 'Hospitech',
                'company_description' => 'Hospitality and customer support services.',
                'company_address' => 'Jl. Raya Gedeg No.10',
                'social_media_company' => '@hospitech',
                'company_industry' => 'Hospitality',
                'company_logo_image' => null,
                'email_company' => 'hrd@hospitech.com',
                'no_wa_company' => '081299988877',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Graphic Designer',
                'category_job' => 'Design & Creative',
                'job_type' => 'Contract',
                'place_work' => 'Remote',
                'type_gender' => 'Any',
                'education_minimal' => 'Diploma',
                'experience_minimal' => '1 year',
                'age' => '20-30',
                'job_description' => 'Create visual designs for marketing campaigns.',
                'job_requirements' => 'Adobe Photoshop, Illustrator',
                'salary_minimal_range' => 4000000,
                'maximum_salary_range' => 6000000,
                'location' => 'Mojoanyar',
                'image_banner' => null,
                'company_name' => 'Creative Studio',
                'company_description' => 'Design agency specializing in branding.',
                'company_address' => 'Jl. Mojoanyar No.8',
                'social_media_company' => '@creative_studio',
                'company_industry' => 'Design',
                'company_logo_image' => null,
                'email_company' => 'jobs@creativestudio.com',
                'no_wa_company' => '081277766655',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Logistics Coordinator',
                'category_job' => 'Transportation & Logistic',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Any',
                'education_minimal' => 'Bachelor Degree',
                'experience_minimal' => '3 years',
                'age' => '27-40',
                'job_description' => 'Coordinate and manage shipment logistics.',
                'job_requirements' => 'Supply chain knowledge, planning skills',
                'salary_minimal_range' => 5500000,
                'maximum_salary_range' => 7500000,
                'location' => 'Trowulan',
                'image_banner' => null,
                'company_name' => 'LogiTrans',
                'company_description' => 'Leading logistics service provider.',
                'company_address' => 'Jl. Trowulan No.12',
                'social_media_company' => '@logitrans',
                'company_industry' => 'Logistics',
                'company_logo_image' => null,
                'email_company' => 'career@logitrans.com',
                'no_wa_company' => '081255577799',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'HR Officer',
                'category_job' => 'HR & Recruiting',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Any',
                'education_minimal' => 'Bachelor Degree',
                'experience_minimal' => '2 years',
                'age' => '25-35',
                'job_description' => 'Manage recruitment and employee relations.',
                'job_requirements' => 'HR software, communication skills',
                'salary_minimal_range' => 4500000,
                'maximum_salary_range' => 6500000,
                'location' => 'Pacet',
                'image_banner' => null,
                'company_name' => 'PeopleFirst',
                'company_description' => 'HR consulting services.',
                'company_address' => 'Jl. Kabupaten No. 20',
                'social_media_company' => '@peoplefirst',
                'company_industry' => 'Human Resources',
                'company_logo_image' => null,
                'email_company' => 'hr@peoplefirst.com',
                'no_wa_company' => '081234567800',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Finance Analyst',
                'category_job' => 'Finance & Accounting',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Any',
                'education_minimal' => 'Bachelor Degree',
                'experience_minimal' => '3 years',
                'age' => '26-36',
                'job_description' => 'Analyze financial data and prepare reports.',
                'job_requirements' => 'Excel, financial modeling',
                'salary_minimal_range' => 6000000,
                'maximum_salary_range' => 8500000,
                'location' => 'Jetis',
                'image_banner' => null,
                'company_name' => 'FinCorp',
                'company_description' => 'Finance and investment company.',
                'company_address' => 'Jl. Jetis No. 15',
                'social_media_company' => '@fincorp',
                'company_industry' => 'Finance',
                'company_logo_image' => null,
                'email_company' => 'finance@fincorp.com',
                'no_wa_company' => '081245678901',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Teacher - Elementary School',
                'category_job' => 'Education & Training',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Female',
                'education_minimal' => 'Bachelor Degree',
                'experience_minimal' => '2 years',
                'age' => '24-34',
                'job_description' => 'Teach basic subjects to elementary students.',
                'job_requirements' => 'Teaching certification',
                'salary_minimal_range' => 3500000,
                'maximum_salary_range' => 5000000,
                'location' => 'Pungging',
                'image_banner' => null,
                'company_name' => 'Bright Future School',
                'company_description' => 'Elementary education institution.',
                'company_address' => 'Jl. Pungging No. 7',
                'social_media_company' => '@brightfuture',
                'company_industry' => 'Education',
                'company_logo_image' => null,
                'email_company' => 'info@brightfuture.edu',
                'no_wa_company' => '081266677788',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Food & Beverage Supervisor',
                'category_job' => 'Food & Beverage',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Any',
                'education_minimal' => 'Diploma',
                'experience_minimal' => '3 years',
                'age' => '28-38',
                'job_description' => 'Supervise restaurant operations and staff.',
                'job_requirements' => 'Leadership skills, F&B knowledge',
                'salary_minimal_range' => 4500000,
                'maximum_salary_range' => 6000000,
                'location' => 'Bangsal',
                'image_banner' => null,
                'company_name' => 'TasteBuds',
                'company_description' => 'Restaurant and catering service.',
                'company_address' => 'Jl. Bangsal No. 3',
                'social_media_company' => '@tastebuds',
                'company_industry' => 'Food & Beverage',
                'company_logo_image' => null,
                'email_company' => 'hr@tastebuds.com',
                'no_wa_company' => '081299900011',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Social Media Specialist',
                'category_job' => 'Marketing & Socmed',
                'job_type' => 'Contract',
                'place_work' => 'Remote',
                'type_gender' => 'Any',
                'education_minimal' => 'Bachelor Degree',
                'experience_minimal' => '1 year',
                'age' => '22-32',
                'job_description' => 'Manage social media channels and campaigns.',
                'job_requirements' => 'Social media tools, content creation',
                'salary_minimal_range' => 4000000,
                'maximum_salary_range' => 5500000,
                'location' => 'Mojosari',
                'image_banner' => null,
                'company_name' => 'SocialBuzz',
                'company_description' => 'Digital marketing agency.',
                'company_address' => 'Jl. Mojosari No. 9',
                'social_media_company' => '@socialbuzz',
                'company_industry' => 'Marketing',
                'company_logo_image' => null,
                'email_company' => 'careers@socialbuzz.com',
                'no_wa_company' => '081233322211',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Electrical Technician',
                'category_job' => 'Pekerjaan Teknis',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Male',
                'education_minimal' => 'Diploma',
                'experience_minimal' => '3 years',
                'age' => '25-35',
                'job_description' => 'Maintain and repair electrical systems.',
                'job_requirements' => 'Technical knowledge, safety compliance',
                'salary_minimal_range' => 5000000,
                'maximum_salary_range' => 7000000,
                'location' => 'Sooko',
                'image_banner' => null,
                'company_name' => 'ElectroTech',
                'company_description' => 'Electrical maintenance services.',
                'company_address' => 'Jl. Sooko No. 4',
                'social_media_company' => '@electrotech',
                'company_industry' => 'Technical Services',
                'company_logo_image' => null,
                'email_company' => 'jobs@electrotech.com',
                'no_wa_company' => '081244455566',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Retail Store Manager',
                'category_job' => 'Retail & Merchandising',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Any',
                'education_minimal' => 'Diploma',
                'experience_minimal' => '4 years',
                'age' => '30-45',
                'job_description' => 'Manage daily store operations and sales targets.',
                'job_requirements' => 'Leadership, sales experience',
                'salary_minimal_range' => 6000000,
                'maximum_salary_range' => 9000000,
                'location' => 'Ngoro',
                'image_banner' => null,
                'company_name' => 'RetailMax',
                'company_description' => 'Retail chain across the region.',
                'company_address' => 'Jl. Ngoro No. 18',
                'social_media_company' => '@retailmax',
                'company_industry' => 'Retail',
                'company_logo_image' => null,
                'email_company' => 'hr@retailmax.com',
                'no_wa_company' => '081266688899',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Medical Laboratory Technician',
                'category_job' => 'Health & Science',
                'job_type' => 'Full-Time',
                'place_work' => 'On-site',
                'type_gender' => 'Any',
                'education_minimal' => 'Diploma',
                'experience_minimal' => '2 years',
                'age' => '24-34',
                'job_description' => 'Perform laboratory tests and analysis.',
                'job_requirements' => 'Lab certification, attention to detail',
                'salary_minimal_range' => 4500000,
                'maximum_salary_range' => 6000000,
                'location' => 'Pacet',
                'image_banner' => null,
                'company_name' => 'HealthLab',
                'company_description' => 'Healthcare laboratory services.',
                'company_address' => 'Jl. Pacet No. 21',
                'social_media_company' => '@healthlab',
                'company_industry' => 'Healthcare',
                'company_logo_image' => null,
                'email_company' => 'contact@healthlab.com',
                'no_wa_company' => '081299912345',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        DB::table('lowongan')->insert($dummyJobs);
    }
}
