<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use Illuminate\Support\Carbon; // Tambahkan ini di bagian atas

class LowonganSeeder extends Seeder
{
    public function run(): void
    {
        // Hapus data lama
        DB::table('lowongan')->truncate();
        $now = Carbon::now();

        $dummyJobs = [
            [
                'job_name' => 'Graphic Designer',
                'category_job' => 'Design & Creative',
                'job_type' => 'Freelance',
                'place_work' => 'Remote',
                'type_gender' => 'Any',
                'education_minimal' => 'D1-D3',
                'experience_minimal' => '1 year',
                'age' => '20-30',
                'job_description' => 'Create visual designs for marketing campaigns.',
                'job_requirements' => 'Adobe Photoshop, Illustrator',
                'salary_minimal_range' => 4000000,
                'maximum_salary_range' => 6000000,
                'location' => 'Mojoanyar',
                'image_banner' => null,
                'company_name' => 'Creative Studio',
                'company_description' => 'Design agency specializing in branding.',
                'company_address' => 'Jl. Mojoanyar No.8',
                'social_media_company' => '@creative_studio',
                'company_industry' => 'Design',
                'company_logo_image' => null,
                'email_company' => 'jobs@creativestudio.com',
                'no_wa_company' => '081277766655',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Sales Executive',
                'category_job' => 'Business Dev & Sales',
                'job_type' => 'Fulltime',
                'place_work' => 'Onsite',
                'type_gender' => 'Any',
                'education_minimal' => 'SMA/K',
                'experience_minimal' => '2 years',
                'age' => '22-35',
                'job_description' => 'Menjual produk ke pelanggan dan mencapai target bulanan.',
                'job_requirements' => 'Komunikasi bagus, negosiasi, SIM C',
                'salary_minimal_range' => 3500000,
                'maximum_salary_range' => 5000000,
                'location' => 'Prajurit Kulon',
                'image_banner' => null,
                'company_name' => 'Maju Jaya Elektronik',
                'company_description' => 'Toko elektronik skala lokal.',
                'company_address' => 'Jl. Letkol Sumarjo No.15',
                'social_media_company' => '@majuelektronik',
                'company_industry' => 'Retail',
                'company_logo_image' => null,
                'email_company' => 'rekrut@majujaya.co.id',
                'no_wa_company' => '082122334455',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Admin Gudang',
                'category_job' => 'Admin & Operations',
                'job_type' => 'Fulltime',
                'place_work' => 'Onsite',
                'type_gender' => 'Any',
                'education_minimal' => 'SMA/K',
                'experience_minimal' => '1 year',
                'age' => '20-30',
                'job_description' => 'Input data keluar masuk barang dan pengecekan stok.',
                'job_requirements' => 'Teliti, Microsoft Excel',
                'salary_minimal_range' => 3200000,
                'maximum_salary_range' => 4000000,
                'location' => 'Magersari',
                'image_banner' => null,
                'company_name' => 'Gudang Makmur',
                'company_description' => 'Distribusi sembako wilayah Mojokerto.',
                'company_address' => 'Jl. Pahlawan No. 22',
                'social_media_company' => '@gudangmakmur',
                'company_industry' => 'Logistic',
                'company_logo_image' => null,
                'email_company' => 'hrd@gudangmakmur.co.id',
                'no_wa_company' => '081122334466',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Waiter/Waitress',
                'category_job' => 'CS & Hospitality',
                'job_type' => 'Parttime',
                'place_work' => 'Onsite',
                'type_gender' => 'Any',
                'education_minimal' => 'SMA/K',
                'experience_minimal' => '0 year',
                'age' => '18-25',
                'job_description' => 'Melayani tamu restoran dan menyajikan makanan.',
                'job_requirements' => 'Ramah, disiplin, cepat belajar',
                'salary_minimal_range' => 2000000,
                'maximum_salary_range' => 3000000,
                'location' => 'Jetis',
                'image_banner' => null,
                'company_name' => 'Resto Mojopahit',
                'company_description' => 'Restoran keluarga khas Jawa.',
                'company_address' => 'Jl. Mojopahit No.1',
                'social_media_company' => '@restomojopahit',
                'company_industry' => 'F&B',
                'company_logo_image' => null,
                'email_company' => 'info@restomojopahit.com',
                'no_wa_company' => '081355667788',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Sopir Pengiriman',
                'category_job' => 'Transportation & Logistic',
                'job_type' => 'Fulltime',
                'place_work' => 'Onsite',
                'type_gender' => 'Male',
                'education_minimal' => 'SMA/K',
                'experience_minimal' => '1 year',
                'age' => '21-40',
                'job_description' => 'Mengantar barang ke wilayah Mojokerto dan sekitarnya.',
                'job_requirements' => 'SIM B1, hafal jalan lokal',
                'salary_minimal_range' => 4000000,
                'maximum_salary_range' => 5500000,
                'location' => 'Bangsal',
                'image_banner' => null,
                'company_name' => 'CV Logistik Bersama',
                'company_description' => 'Perusahaan jasa logistik lokal.',
                'company_address' => 'Jl. Raya Bangsal No.5',
                'social_media_company' => '@logistikbersama',
                'company_industry' => 'Logistic',
                'company_logo_image' => null,
                'email_company' => 'logistik@bersama.co.id',
                'no_wa_company' => '085677889900',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Guru Bahasa Inggris',
                'category_job' => 'Education & Training',
                'job_type' => 'Fulltime',
                'place_work' => 'Onsite',
                'type_gender' => 'Any',
                'education_minimal' => 'S1/D4',
                'experience_minimal' => '2 years',
                'age' => '23-40',
                'job_description' => 'Mengajar Bahasa Inggris tingkat SMP-SMA.',
                'job_requirements' => 'TOEFL min. 550, pengalaman mengajar',
                'salary_minimal_range' => 4500000,
                'maximum_salary_range' => 6000000,
                'location' => 'Trowulan',
                'image_banner' => null,
                'company_name' => 'Lembaga Bahasa Global',
                'company_description' => 'Lembaga kursus bahasa asing.',
                'company_address' => 'Jl. Veteran No.10',
                'social_media_company' => '@globalenglishmjkt',
                'company_industry' => 'Education',
                'company_logo_image' => null,
                'email_company' => 'karir@globalenglish.com',
                'no_wa_company' => '087822334455',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Digital Marketing Specialist',
                'category_job' => 'Marketing & Socmed',
                'job_type' => 'Fulltime',
                'place_work' => 'Hybrid',
                'type_gender' => 'Any',
                'education_minimal' => 'S1/D4',
                'experience_minimal' => '2 years',
                'age' => '23-35',
                'job_description' => 'Mengelola kampanye digital dan sosial media.',
                'job_requirements' => 'Facebook Ads, SEO, Canva',
                'salary_minimal_range' => 5000000,
                'maximum_salary_range' => 7000000,
                'location' => 'Magersari',
                'image_banner' => null,
                'company_name' => 'PT Digital Mojokerto',
                'company_description' => 'Startup digital agency lokal Mojokerto.',
                'company_address' => 'Jl. Majapahit No.23',
                'social_media_company' => '@digitalmjkt',
                'company_industry' => 'Marketing',
                'company_logo_image' => null,
                'email_company' => 'hr@digitalmjkt.com',
                'no_wa_company' => '082277889900',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Software Engineer',
                'category_job' => 'IT & Engineering',
                'job_type' => 'Fulltime',
                'place_work' => 'Remote',
                'type_gender' => 'Any',
                'education_minimal' => 'S1/D4',
                'experience_minimal' => '3 years',
                'age' => '23-35',
                'job_description' => 'Membangun dan mengembangkan aplikasi berbasis web.',
                'job_requirements' => 'Laravel, Vue.js, PostgreSQL',
                'salary_minimal_range' => 8000000,
                'maximum_salary_range' => 12000000,
                'location' => 'Remote',
                'image_banner' => null,
                'company_name' => 'PT Teknologi Nusantara',
                'company_description' => 'Perusahaan pengembang perangkat lunak.',
                'company_address' => 'Jl. Nasional No.99',
                'social_media_company' => '@teknonusantara',
                'company_industry' => 'IT',
                'company_logo_image' => null,
                'email_company' => 'karir@teknonusantara.id',
                'no_wa_company' => '081344556677',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Perawat Klinik',
                'category_job' => 'Health & Science',
                'job_type' => 'Fulltime',
                'place_work' => 'Onsite',
                'type_gender' => 'Female',
                'education_minimal' => 'D1-D3',
                'experience_minimal' => '1 year',
                'age' => '22-35',
                'job_description' => 'Melakukan perawatan pasien dan administrasi klinik.',
                'job_requirements' => 'STR aktif, ramah',
                'salary_minimal_range' => 4000000,
                'maximum_salary_range' => 5500000,
                'location' => 'Sooko',
                'image_banner' => null,
                'company_name' => 'Klinik Sehat Bersama',
                'company_description' => 'Klinik layanan kesehatan umum.',
                'company_address' => 'Jl. Raya Sooko No.9',
                'social_media_company' => '@kliniksehatmjkt',
                'company_industry' => 'Healthcare',
                'company_logo_image' => null,
                'email_company' => 'rekrutmen@kliniksehat.com',
                'no_wa_company' => '082177889900',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Teknisi AC',
                'category_job' => 'Technical Work',
                'job_type' => 'Freelance',
                'place_work' => 'Onsite',
                'type_gender' => 'Male',
                'education_minimal' => 'SMA/K',
                'experience_minimal' => '2 years',
                'age' => '20-40',
                'job_description' => 'Perawatan dan perbaikan AC rumah dan kantor.',
                'job_requirements' => 'Paham kelistrikan, pengalaman teknis',
                'salary_minimal_range' => 1500000,
                'maximum_salary_range' => 5000000,
                'location' => 'Puri',
                'image_banner' => null,
                'company_name' => 'CV Dingin Sentosa',
                'company_description' => 'Layanan servis pendingin Mojokerto.',
                'company_address' => 'Jl. Rajekwesi No.10',
                'social_media_company' => '@dinginsentosa',
                'company_industry' => 'Home Service',
                'company_logo_image' => null,
                'email_company' => 'service@dinginsentosa.co.id',
                'no_wa_company' => '081266778899',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'HR Generalist',
                'category_job' => 'HR & Recruiting',
                'job_type' => 'Fulltime',
                'place_work' => 'Onsite',
                'type_gender' => 'Any',
                'education_minimal' => 'S1/D4',
                'experience_minimal' => '2 years',
                'age' => '25-35',
                'job_description' => 'Rekrutmen, pelatihan, dan pengelolaan data karyawan.',
                'job_requirements' => 'Komunikasi bagus, leadership',
                'salary_minimal_range' => 5000000,
                'maximum_salary_range' => 7000000,
                'location' => 'Magersari',
                'image_banner' => null,
                'company_name' => 'PT Mojokerto Humanindo',
                'company_description' => 'Perusahaan konsultan SDM.',
                'company_address' => 'Jl. Bhayangkara No.5',
                'social_media_company' => '@mojohumanindo',
                'company_industry' => 'HR Consulting',
                'company_logo_image' => null,
                'email_company' => 'karir@mojohumanindo.com',
                'no_wa_company' => '082333445566',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Kasir Toko Fashion',
                'category_job' => 'Retail & Merchandising',
                'job_type' => 'Parttime',
                'place_work' => 'Onsite',
                'type_gender' => 'Female',
                'education_minimal' => 'SMA/K',
                'experience_minimal' => '0 year',
                'age' => '18-25',
                'job_description' => 'Melayani pembayaran dan pembukuan kas.',
                'job_requirements' => 'Jujur, teliti, ramah',
                'salary_minimal_range' => 1800000,
                'maximum_salary_range' => 2500000,
                'location' => 'Kota Mojokerto',
                'image_banner' => null,
                'company_name' => 'Fashionku',
                'company_description' => 'Toko pakaian wanita lokal.',
                'company_address' => 'Jl. Benteng Pancasila No.7',
                'social_media_company' => '@fashionkumjkt',
                'company_industry' => 'Retail',
                'company_logo_image' => null,
                'email_company' => 'fashionku@gmail.com',
                'no_wa_company' => '081244556677',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'job_name' => 'Analis Data Junior',
                'category_job' => 'Data & Product',
                'job_type' => 'Internship',
                'place_work' => 'Remote',
                'type_gender' => 'Any',
                'education_minimal' => 'S1/D4',
                'experience_minimal' => '0 year',
                'age' => '20-28',
                'job_description' => 'Membantu analisis data penjualan dan laporan.',
                'job_requirements' => 'Excel, SQL dasar',
                'salary_minimal_range' => 1000000,
                'maximum_salary_range' => 1500000,
                'location' => 'Remote',
                'image_banner' => null,
                'company_name' => 'DataInsight ID',
                'company_description' => 'Startup analisis data.',
                'company_address' => 'Jl. Data Nasional No.12',
                'social_media_company' => '@datainsightid',
                'company_industry' => 'Data Technology',
                'company_logo_image' => null,
                'email_company' => 'rekrut@datainsight.id',
                'no_wa_company' => '081266889900',
                'delivery_limit' => now()->addMonth(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('lowongan')->insert($dummyJobs);
    }
}
